### ISSUE TITLE
User-Defined Meta Description on Blog Posts

### ISSUE THREAD

**Issue by tabitagreen** [carleton/reason_package#105]
As a website content creator I want to be able to add a meta description to individual blog posts to improve user click-throughs from search results. Recommend adding a "Metadata" section for posts like we have for pages.

Acceptance Criteria
- Make sure user has a field "Description" on the "Adding News / Post" page in which to enter meta description.
- Make sure the Description field shows the character count. (This is how it works for pages.)
- Make sure the content in the Description field populates the meta description tag on the post.
- Make sure the meta description tag updates when a user updates the Description field is edited.

**Comment by slylth** [comment]
The description field is already used as the posts teaser text (i.e. before the "Read More" link). Should this be a new metadata-description field or can the same content be used?

**Comment by slylth** [comment]
#191
