### ISSUE TITLE
Content change detection 5 second delay removal

### ISSUE THREAD

**Issue by wilburb** [carleton/reason_package#12]
Tiny MCE and content change detection can likely work without the 5 second delay (in place due to loki). Above the iframe that becomes the TinyMCE editor the initial text area is populated. This could be used to compare to TinyMCE's contents. Right now a 5 second delay occurs, the page's form data is serialized. Loki and TinyMCE iframes are dug through to find the content, and they are serialized along with the rest of the form.

Another check could be put in place to check that TinyMCE's content matches the text area above the iframe, alongside of comparing to the initial serialized data, thus eliminating the need for a 5 second delay with everything except for loki.

**Comment by slylth** [comment]
Dependent on Loki replacement.

**Comment by mryand** [comment]
Closing in favor ot CKEditor integration
