### ISSUE TITLE
Social media icons don't display in default theme

### ISSUE THREAD

**Issue by huintr01** [carleton/reason_package#128]
I tried to add the social media accounts both through the Master Admin interface and the content type and neither showed up in the default theme.
- Tested in Reason 4.6
- Tested in Chrome and Firefox
- OS X Yosemite

**Comment by slylth** [comment]
Maybe related to #136. Pull request #102.

**Comment by mryand** [comment]
This may be a misunderstanding of the way social accounts work. There is a module that displays social accounts; by default templates don't display them. Social account display *can* be embedded into a template by either modifying page types at the template level to always include this module in a dedicated page location, or by directly using the social account api to produce the necessary markup. In any case, if you want to see social accounts displaying you can use the social_accounts page type, which I just added (apparently there were not core page types that used the social_accounts module, which this commit fixes: 29a07f41669e4a7e5981288509137059639001aa)

**Comment by mryand** [comment]
If wewant the default template to display social accounts I'd recommend making it a feature request for 4.7.

**Comment by slylth** [comment]
Closing this and we'll open a new issue if we want to add social accounts to the default template.
