### ISSUE TITLE
Faculty not appearing on default theme

### ISSUE THREAD

**Issue by huintr01** [carleton/reason_package#129]
Upon creating a new faculty page and setting it to the "Faculty" page type and after adding new faculty members, they don't appear on the page.
Example of issue: https://reasontest46.luther.edu/faculty/
- Tested in Reason 4.6
- Tested in Chrome and Firefox
- OS X Yosemite

**Comment by slylth** [comment]
Doesn't work if theme is changed, either.

**Comment by slylth** [comment]
Working. This was a misunderstanding of how the Faculty/Staff module works. The module only displays pulled from a data source (ldap or reason). The module will not display a username (first required field) that is not present in either data source.
