### ISSUE TITLE
YouTube videos as media files/works not appearing on pages, events, or news posts on default theme

### ISSUE THREAD

**Issue by huintr01** [carleton/reason_package#130]
Page example: https://reasontest46.luther.edu/test/
Event example: https://reasontest46.luther.edu/events/?event_id=241474&date=2015-06-30
News post example: https://reasontest46.luther.edu/blog/?story_id=241540

Tested in Reason 4.6. Followed the same procedure as how we add YouTube videos on our Luther instance of Reason. Tested in Firefox and Chrome.

**Comment by slylth** [comment]
This may be a Luther-specific problem.

**Comment by slylth** [comment]
@mryand Can you check for youtube responsive/html5 setting in Carleton code?

**Comment by mryand** [comment]
In settings/media_integration/media_settings.php, add 'youtube' to the $GLOBALS['NEW_MEDIA_WORK_INTEGRATION_LIBRARIES' array].

**Comment by mryand** [comment]
This appears to be fixed in the 4.6 branch.
