### ISSUE TITLE
TinyMCE toolbar missing button to add horizontal rule

### ISSUE THREAD

**Issue by huintr01** [carleton/reason_package#131]
![toolbar](https://cloud.githubusercontent.com/assets/5932682/7502228/0ac788fc-f400-11e4-8de7-0390d741b654.jpg)
Tested in Reason 4.6.

**Comment by slylth** [comment]
Tables are present with a different setting in the html editor settings on the site setup. 

![screen shot 2015-05-06 at 3 24 23 pm](https://cloud.githubusercontent.com/assets/1071533/7502764/133cdfd8-f404-11e4-92df-2036b1e73c98.png)

```<hr>``` should be added to the list

**Comment by mryand** [comment]
Is this change in the test instance?

**Comment by mryand** [comment]
Hmmm. I just checked, and it looks like it's not on the test instance. The code looks fine to me (not that I really understand Tiny configuration).
