### ISSUE TITLE
Attempt to log in to /reason/admin/ redirects to server root

### ISSUE THREAD

**Issue by mryand** [carleton/reason_package#135]
I go to https://reasontest46.luther.edu/reason/admin/, get prompted for log in, and log in. I then get redirected to the server root rather than to the admin page. I should instead get redirected to the admin interface.

**Comment by slylth** [comment]
This was a configuration problem. ```HTTPS_AVAILABLE``` was set to false and I was trying to fix via apache. There is no bug.
