### ISSUE TITLE
Not seeing linkedin among the available social media account types when creating a social account

### ISSUE THREAD

**Issue by mryand** [carleton/reason_package#136]
#102 adds linked in social media integration. I can add a LinkedIn account if I manually modify the query string, but the interface doesn't give me an option to choose linkedin -- just FB, G+, & Instagram.

**Comment by mryand** [comment]
![social_account](https://cloud.githubusercontent.com/assets/256007/7618625/fb2cb358-f978-11e4-871b-91b83473420d.png)

**Comment by slylth** [comment]
Is twitter also missing?

**Comment by mryand** [comment]
Yes, Twitter also seems to be missing. I can investigate if you give me a login on the test server.

**Comment by mryand** [comment]
Just committed 316313dc11fc1aa55d715c21ca6de4b4c85623aa, which should fix this. Steve, can you review?

**Comment by slylth** [comment]
Looks good.
