### ISSUE TITLE
Ability to have multiple email recipients for Event registration slots

### ISSUE THREAD

**Issue by huintr01** [carleton/reason_package#146]
We're looking for the ability similar to forms in Reason to have multiple people receive email notifications upon someone registering for an event.

**Comment by slylth** [comment]
Possible content_manager error_check fix.

**Comment by mheiman** [comment]
Slot registration notifications are sent to the person listed as the contact for the event, which currently requires a single username.  Allowing that to be multiple will also require updating all of the code that uses or displays that contact field.

**Comment by mheiman** [comment]
Carleton has significant custom code relying on a singular event contact.  Looking at this more closely, I'm thinking it would make more sense to add a notification email field to the registration slot itself.  That would allow notifications to go to multiple people, and the person(s) receiving notification could be different from the public contact for the event.  Notification could also be disabled ( not currently possibly without removing the event contact ) by leaving the new field empty.

The upgrade script should probably update all existing registration slots to contain the contact name from the associated event to prevent any interruption of notifications.
