### ISSUE TITLE
VM: Instructions don't work smoothly

### ISSUE THREAD

**Issue by mryand** [carleton/reason_package#147]
On a new download of the VM, the login message says to switch to the reason_package directory, perform "git checkout master", then "git pull".

But when I perform "git checkout master" it says I have a changes in reason_4.0/classes/version_check.php, settings/dbs.xml, and settings/error_handler_settings.php, preventing a checkout.

I imagine most of these are necessary changes for the function of the VM, but it's not a great experience to not be able to follow the instructions provided.

**Comment by slylth** [comment]
error_handler_settings.php and version_check.php is now up-to-date. I committed dbs.xml locally to avoid the conflict.
