### ISSUE TITLE
VM: Fatal error on site finish

### ISSUE THREAD

**Issue by mryand** [carleton/reason_package#148]
In a fresh download of the Reason VM, there is a fatal error when you finish out of a site.

To reproduce:

1. Download and install the Reason VM
2. Create a new site, or edit an existing site. Make edits (or not)
3. Click "Finish" It should complete and go back to the site list. Instead you get an "Oops" message.

**Comment by mryand** [comment]
I've noticed that there appear to be a host of permissions problems on the VM, which prevent sized images from working properly and generated css from being placed in a web-available location. It appears the web temp directory is not apache-writable.

**Comment by slylth** [comment]
I'll look at this when doing the final packaging for 4.6.

**Comment by mryand** [comment]
some aggressive permissions stuff seems to have fixed it in my copy of the vm. I ran these in both reason_package/ and html/:

chgrp apache * -Rf
chmod g+w * -Rf

**Comment by slylth** [comment]
Changed the permissions.
