### ISSUE TITLE
New form builder bug/unintended use scenario?

### ISSUE THREAD

**Issue by huintr01** [carleton/reason_package#149]
While testing the new form builder, it first seemed to me that I could simply drag the green form fields into the form and build it that way. It does indeed let me drag them into the form area, but they're unable to be edited. I realize that the intended route is to first click the green form fields and then enter the information before they're added to the form.

It's even more confusing to user then because the blank form fields dragged to the form can't be edited or deleted (unless they refresh or save the form and then they disappear).

**Comment by huintr01** [comment]
I also wanted to mention I found it confusing that the field confirmation button to confirm it being ready to add is titled "Add Another Field". While I understand that I can add more fields, it may be confusing to a user that doesn't wish to add another field after the current one they're working on. Maybe something truer to what the button actually does like "Add Field", etc.

**Comment by mryand** [comment]
The dragging issue sounds like a genuine bug. You should be able to either click on items or drag them onto the form area.

**Comment by DookTibsCarl** [comment]
Yea - that is correct. I’m taking a look at this now.

-Tom

**Comment by slylth** [comment]
https://github.com/carleton/reason_package/commit/81f88e9862c53f3db6c3a2da94e83ac055e193a8
