### ISSUE TITLE
Form Response Options change from previous version

### ISSUE THREAD

**Issue by huintr01** [carleton/reason_package#150]
In the past we've been able to have forms both save responses in Reason and send an email notification. While testing the new form version, I tried setting the form to save in Reason but also included an email thinking it would do that as well. I never received an email after submitting a form entry.

Does the new form version only allow one or the other option?

**Comment by mryand** [comment]
There weren't any changes like that. It's most likely that sendmail isn't configured in the test server. If Steve Smith was around he'd be the person to look at it...

**Comment by huintr01** [comment]
Ah that makes sense, thanks Matt!
