### ISSUE TITLE
Get TinyMCE to point where we can drop Loki

### ISSUE THREAD

**Issue by mryand** [carleton/reason_package#154]
We'll need to develop a list of what is needed for this to be possible -- let's develop that in the comments on this issue.

**Comment by mryand** [comment]
#12 depends on this

**Comment by mryand** [comment]
#132 is part of this

**Comment by tabitagreen** [comment]
Gap analysis (based on what Luther currently has turned on for admins compared to the admin interface in reasoncms.org):
- Cut (don't need)
- Copy (don't need)
- Paste (don't need)
- Highlight (nice to have)
- Indent (use tab for lists)
- Outdent (use tab for lists)
- Insert Table (need)

Linking gaps:
- List of all sites (need)
- Link to asset (nice to have - our SID will pitch a fit if we don't have it)
- Link to events (nice to have)
- Link to News/Posts (nice to have)
- Link to anchors (need) - it looks like the functionality is partially there...

**Comment by mryand** [comment]
Closing in favor of CKEditor integration
