### ISSUE TITLE
Multiple Features per page

### ISSUE THREAD

**Issue by slylth** [carleton/reason_package#170]
Allow for multiple features on a page using a categories as a page location mechanism. If an acceptable_param of 'categories' is set, then the module will only display features of that category.

### Acceptance Criteria
- Able to attach multiple features/page
- Upgrade script to add a feature_to_category allowable relationship
  - many-to-many
  - bi-directional
  - sortable
  - not required
- Offset timer acceptable_param 
  - used in conjunction with autoplay_timer so all features can rotate individually
  - default is no offset
- Javascript handles multiple features per page

**Comment by mryand** [comment]
Steve says that this is close to done at Luther.
