### ISSUE TITLE
Social Account View unable to specify in page type

### ISSUE THREAD

**Issue by slylth** [carleton/reason_package#175]
Using page type parameters, you are not able to override the default view for a social_account module
```php
'sidebar' => array(
  'module' => 'social_account/social_account',
  'view' => 'social_account/view/my_view.php',
),
```

**Comment by mryand** [comment]
Steve says this is done.

**Comment by slylth** [comment]
https://github.com/carleton/reason_package/commit/f6a1abb1628b5bedc3c046e0d4999b6f08fb0114
