### ISSUE TITLE
Emails Sent with Tyr fail: "Multiple or malformed newlines"

### ISSUE THREAD

**Issue by mischler** [carleton/reason_package#189]
After doing our recent server move, we realized that Reason forms were not sending notification emails.  Part of the issue is our server configuration, but I came across this error popping up in [Tyr's email.php file](https://github.com/carleton/reason_package/blob/master/tyr/email.php) on submission:

    Warning: mail(): Multiple or malformed newlines found in additional_header at …/tyr/email.php:125

I tracked cause of the error down to [a security fix made to PHP](http://stackoverflow.com/questions/30887610/error-with-php-mail-multiple-or-malformed-newlines-found-in-additional-header) which prevent multiple newlines.  As far as I understand it, a single newline is used to denote the separation of headers and email, and additional newlines can be used for injection.  

Presently, the call to the `mail()` function depends on whether or not the server is Window or Linux.  The Linux call concatenates the headers and email into a single parameter, wherein multiple newlines between the two result in the error given above.  My solution for the problem was to use the call to the `mail()` function currently designated for Windows (line 170) for any email (as hinted by the comment in line 168):

    168    // it seems a little odd that we are sending the whole email in via the additional headers parameter when not running windows
    169    $success = (server_is_windows())
    170        ? mail('', $subject, $email, $additional_headers )
    171        : mail('', $subject, '', $additional_headers.$email );

becomes

    168    $success = mail('', $subject, $email, $additional_headers );

I see Tyr is likely to be replaced soon (#164), but this change in PHP behavior would be something to keep an eye out for while still using Tyr and when moving forward to whatever will/may replace it.

**Comment by mischler** [comment]
I mark it as an issue in case there's another approach deemed more ideal than my quick attempt to fix the issue.

**Comment by slylth** [comment]
recheck with the new Tyr replacement @laupow

**Comment by laupow** [comment]
This issue is resolved following the integration of PHPMailer

On Sun, Jun 26, 2016 at 7:03 PM, Steve Smith <notifications@github.com>
wrote:

> recheck with the new Tyr replacement @laupow <https://github.com/laupow>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/carleton/reason_package/issues/189#issuecomment-228631329>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGXXAL1utC0mLwmAd2LspRmFeRsEna_sks5qPxM0gaJpZM4HBgC_>
> .
>



-- 
Matt Lauer
Web Administrator/Developer
Carleton College
