### ISSUE TITLE
Problems with pagination and searching in master admin

### ISSUE THREAD

**Issue by brifishjones** [carleton/reason_package#54]
See https://groups.google.com/forum/#!topic/reason-discussion/pxHmcP3bStE

In reason_4.0/lib/core/classes/viewer.php there is a method_consult_and_save_session_state(). This method is what allows Reason
to remember what state various admin lists were in, so when you return
to them after editing an item or doing something else you don't have
to re-preform searches, sorts, etc. Given what you describe, I suspect
that there may be a logic error somewhere in that function having to
do with pagination and listers.

**Comment by mryand** [comment]
We need to have a clear way to replicate this before it can really be tackled.
