### ISSUE TITLE
reordering items where some are "not owned or borrowed" unreliable

### ISSUE THREAD

**Issue by natepixel** [carleton/reason_package#6]
In the administrative interface, sometimes an item can be a part of an association, but be "no longer owned or borrowed" by the site. This happens most often when an entity (like a page) is moved from one site to another. When this happens, related images / assets / or whatever do not automatically come along. It becomes possible for a page to then have a relationship with some item that is owned by another site. When this happens, the up and down arrows that control relationship sorting do not appear to work properly. We need to look at how that code functions and make sure it works even for items not owner or borrowed.

**Comment by DookTibsCarl** [comment]
updated reason_package/reason_4.0/lib/core/classes/admin/rel_sort.php to not require an owned/borrowed relationship for the entity selector it uses to verify things. This fixes the issue and allows sorting of items that are neither owned nor borrowed by the site, such as the images on a migrated page in Nate's example.
