### ISSUE TITLE
Open PDFs in browser

### ISSUE THREAD

**Issue by slylth** [carleton/reason_package#93]
Add a setting to allow opening of pdfs in the browser. 
Requirements:
- defaults to false

**Comment by tabitagreen** [comment]
Acceptance Criteria:
- Make sure the default is "false"
- Make sure when setting is set to "false," PDFs do not open in the browser.
- Make sure when setting is changed to "true," PDFs open in a new tab in the browser. 
- Make sure this works on latest versions of Firefox, Chrome, Safari, and IE.
- Test this functionality on a mobile device (at least iOS and Android)

**Comment by mryand** [comment]
A fix for this appears to be in the Carleton pull request for 4.5:

https://github.com/carleton/reason_package/pull/109/files

Look for REASON_PDF_DOWNLOAD_DISPOSITION_DEFAULT

**Comment by slylth** [comment]
Tested and accepted.
