### ISSUE TITLE
Only include site meta keywords if on "real" home page

### ISSUE THREAD

**Issue by mryand** [carleton/reason_package#95]
The site meta keywords get included in this case:

1. The home page is a publication
2. We are looking at a particular story on the publication

One way to resolve this would be to look at the breadcrumbs and only include the site meta keywords if there are no breadcrumb items beyond the page itself.

**Comment by mryand** [comment]
Example:
https://www.luther.edu/magazine/?story_id=592769&issue_id=592276

**Comment by slylth** [comment]
Look and see if this is an issue after keyword setting in 4.6.

**Comment by slylth** [comment]
This seems to be resolved in 4.7-rc
